# Generated by Django 2.1.2 on 2018-11-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bithumb_BTC_1d',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bithumb_BTC_1h',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bithumb_BTC_1m',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('asset', models.FloatField()),
                ('exchange', models.CharField(max_length=20)),
                ('coin', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('strategy', models.CharField(max_length=50)),
                ('autoTrade', models.BooleanField()),
                ('chatBotAlarm', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HighLowStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HighPrice', models.FloatField()),
                ('LowPrice', models.FloatField()),
                ('botId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='ReinforceLearningStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateTimeField()),
                ('toDate', models.DateTimeField()),
                ('coin', models.CharField(max_length=20)),
                ('botId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Running',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=20)),
                ('coin', models.CharField(max_length=20)),
                ('asset', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=5)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('asset', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.CharField(max_length=20)),
                ('endDate', models.CharField(max_length=20)),
                ('coin', models.CharField(max_length=20)),
            ],
        ),
    ]
