package com.crypstal.api.model;

public enum Crypto {
	XEM, SPHR, NAV, GTO, VRC, XVG, DNT, BSD, STEEM, MEME, BCPT, SLS, AID, DGB, NBT, ZRX, KMD, GUP, IOST, BCH, OMG, IQ, BKX, BTC, CVC, IOTA, FTC, BTG, FCT, ARK, RCN, IGNIS, POWR, BLK, VTC, WINGS, CMCT, CFI, RLC, GNO, QRL, BLT, GNT, SC, RDD, ONT, SNT, DYN, PIVX, ARDR, CLOAK, MANA, UBQ, SALT, UKG, STORM, SWT, NMR, ETC, VEE, ETH, MCO, NEO, ZEC, REP, EXCL, LRC, ADA, STORJ, ICX, XZC, ZEN, TIX, LOOM, TX, MTL, PAY, EDG, DOGE, BNT, RVN, LBC, PRO, DASH, RVR, ADT, WAVES, ADX, XRP, SYNX, EMC, TRX, UP, MUE, RFR, TUBE, AMP, LSK, BLOCK, NGC, SYS, SIB, DCR, DCT, KORE, TUSD, LTC, MER, STRAT, ENG, ANT, GBYTE, NXS, UNB, GRS, BURST, NXT, PTOY, SRN, WAX, SHIFT, GAME, SBD, PART, EMC2, XLM, RADS, MFT, OK, QTUM, XDN, LUN, EOS, ION, POLY, BITB, DMT, IOP, HMQ, VIB, VIA, MONA, OST, BAT, BAY, OCN, XMR, EXP, ZIL, XEL
}
